- alias: Amnirana triggered Mobile Push Notification
  trigger:
  - platform: numeric_state
    entity_id: counter.amnirana_motion_detector
    above: 0
  action:
    service: notify.mobile_app_aquila
    data:
      message: Motion was Detected
      title: Amnirana Motion Detection
  id: 429c3d1a12134122a155cfc55c1286df
- alias: '[GLUE] if amnirana input_boolean = off then reset amnirana counter  (a)'
  trigger:
  - platform: state
    entity_id: input_boolean.amnirana_motion_detector
    to: 'off'
  action:
    service: counter.reset
    entity_id: counter.amnirana_motion_detector
  id: 86cbffb159b54eaa85107f800688cb50
- alias: '[GLUE] if amnirana counter = 0 then amnirana input_boolean = off'
  trigger:
  - platform: state
    entity_id: counter.amnirana_motion_detector
    to: '0'
  action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.amnirana_motion_detector
  id: b037f3252ee24a4bb658fe9c540b586a
- id: 4c7fc6ad338247e18b347d675972b2d4
  alias: Arriving Home at night
  trigger:
  - platform: state
    entity_id: person.mathijs
    to: home
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
  - type: turn_on
    device_id: f452c94d32c0e74ff9cf45a8fbd96e77
    entity_id: switch.bedroom_light
    domain: switch
  - type: turn_on
    device_id: 0cd71aab4097cbba429d8e6ce3669c05
    entity_id: switch.mood_wire_light
    domain: switch
  - type: turn_on
    device_id: d32241669db03c603baa5a527aac6c23
    entity_id: light.reading_light
    domain: light
- alias: Went live on twitch
  trigger:
  - platform: state
    entity_id: sensor.frosttusk
    to: streaming
  action:
  - service: notify.frosttusk_twitter
    data:
      message: 'Now live on #twitch {{state_attr("sensor.frosttusk", "title")}}! Tune
        in at https://twitch.tv/FrostTusk for some more #diy #iot content! #twitchstreamers'
  id: bb127bf0d14549e28b76d8873484c917
- id: 2aaf878e344141e1acf6678e0551af45
  alias: Leaving Home
  trigger:
  - platform: state
    entity_id: person.mathijs
    to: not_home
  action:
  - service: switch.turn_off
    entity_id: switch.bedroom_light
  - service: switch.turn_off
    data: {}
    target:
      device_id: aab3d01b268851dc34c32c8a615d4960
  - service: switch.turn_off
    data: {}
    target:
      device_id: 0cd71aab4097cbba429d8e6ce3669c05
  - service: media_player.turn_off
    data: {}
    target:
      device_id: 3718ded81c31df2e8aeb964cbd7203df
  - service: media_player.turn_off
    data: {}
    target:
      device_id: 3db373f99e23c1e16e78d23257583e1f
  - service: media_player.turn_off
    data: {}
    target:
      device_id: e65ca24772253758d2b0c3ee8df46ec1
  - type: turn_off
    device_id: d32241669db03c603baa5a527aac6c23
    entity_id: light.reading_light
    domain: light
- id: '1656201107250'
  alias: Sleepy Time
  description: ''
  trigger: []
  condition: []
  action:
  - type: turn_off
    device_id: aab3d01b268851dc34c32c8a615d4960
    entity_id: switch.desk_light
    domain: switch
  - type: turn_off
    device_id: f452c94d32c0e74ff9cf45a8fbd96e77
    entity_id: switch.bedroom_light
    domain: switch
  - type: turn_off
    device_id: 0cd71aab4097cbba429d8e6ce3669c05
    entity_id: switch.mood_wire_light
    domain: switch
  - type: turn_off
    device_id: d32241669db03c603baa5a527aac6c23
    entity_id: light.reading_light
    domain: light
  - service: media_player.turn_off
    data: {}
    target:
      device_id:
      - e65ca24772253758d2b0c3ee8df46ec1
      - 3db373f99e23c1e16e78d23257583e1f
      - 3718ded81c31df2e8aeb964cbd7203df
  mode: single
