# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# ---
# Entities
# ---
sensor: !include_dir_list malibu-point/entities/sensor
alarm_control_panel: !include_dir_list malibu-point/entities/alarm_control_panel
camera: !include_dir_list malibu-point/entities/camera

glances: !include malibu-point/entities/glances.yaml
tuya: !include malibu-point/entities/tuya.yaml

# ---
# Automations
# ---
automation: !include malibu-point/automations.yaml
script: !include malibu-point/scripts.yaml
scene: !include malibu-point/scenes.yaml

# ---
# Interfaces
# ---
frontend:
  themes: !include_dir_named malibu-point/themes/

google_assistant:
  project_id: home-assistant-140f3
  service_account: !include malibu-point/SERVICE_ACCOUNT.JSON
  report_state: true
  exposed_domains:
    - alarm_control_panel
    - switch
    - camera
  secure_devices_pin: !secret google_secure_devices_pin

# ---
# Other
# ---
group: !include malibu-point/groups.yaml

tts:
  - platform: google_translate
