# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# ---
# Devices
# ---

# sensor:
#   - platform: example_sensor
sensor:
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: disk_use
        arg: /
      - type: disk_free
        arg: /
      - type: memory_use
      - type: memory_free
      - type: swap_use_percent
      - type: swap_use
      - type: swap_free
      - type: load_1m
      - type: load_5m
      - type: load_15m
      - type: throughput_network_in
        arg: enp9s0
      - type: throughput_network_out
        arg: enp9s0
      - type: ipv4_address
        arg: enp9s0
      - type: ipv6_address
        arg: enp9s0
      - type: throughput_network_in
        arg: wlp5s0b1
      - type: throughput_network_out
        arg: wlp5s0b1
      - type: ipv4_address
        arg: wlp5s0b1
      - type: ipv6_address
        arg: wlp5s0b1
      - type: processor_use
      - type: last_boot

alarm_control_panel:
  - platform: smaug
camera:
  - platform: mjpeg
    name: staurois camera
    mjpeg_url: http://192.168.111.182/mjpeg.cgi
    username: !secret staurois_username
    password: !secret staurois_password
    authentication: basic
tuya:
  username: !secret smart_life_username
  password: !secret smart_life_password
  country_code: '32'
  platform: 'smart_life'
glances:
  - host: '192.168.222.221'
    username: !secret glances_ailurus_username
    password: !secret glances_ailurus_password
    name: '(glances) ailurus'
  - host: '192.168.222.164'
    username: !secret glances_panthera_username
    password: !secret glances_panthera_password
    name: '(glances) panthera'
# ---
# Other
# ---

# Text to speech
tts:
  - platform: google_translate

frontend:
  themes: !include_dir_named themes/

google_assistant:
  project_id: home-assistant-140f3
  service_account: !include SERVICE_ACCOUNT.JSON
  report_state: true
  exposed_domains:
    - alarm_control_panel
    - switch
    - camera
  secure_devices_pin: "0"
