# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# ---
# Entities
# ---
sensor: !include_dir_list malibu-point/entities/sensor
alarm_control_panel: !include_dir_list malibu-point/entities/alarm_control_panel
camera: !include_dir_list malibu-point/entities/camera

input_boolean:
  taricha:
    name: taricha tv
input_select:
  taricha:
    name: taricha source
    options:
      - 0
      - 1
      - 2
      - 3
    initial: 0

rest_command:
  turn_on_taricha:
    url: http://192.168.111.181:7896/taricha/on
    method: POST
  turn_off_taricha:
    url: http://192.168.111.181:7896/taricha/off
    method: POST
  select_source_taricha:
    url: http://192.168.111.181:7896/taricha/source
    method: POST
    payload: '{"new_source": {{ source }}}'
    content_type: 'application/json'

media_player:
  - platform: universal
    name: taricha
    children:
      - media_player.hyla
    commands:
      turn_on:
        service: rest_command.turn_on_taricha
      turn_off:
        service: rest_command.turn_off_taricha
      select_source:
        service: rest_command.select_source_taricha
        data_template:
          source: '{{ source }}'
    attributes:
      state: input_boolean.taricha
      source: input_select.taricha
      source_list: "['0', '1', '2', '3']"

    # attributes:
    #   is_volume_muted: ENTITY_ID|ATTRIBUTE
    #   state: ENTITY_ID|ATTRIBUTE

glances: !include malibu-point/entities/glances.yaml
tuya: !include malibu-point/entities/tuya.yaml

# ---
# Automations
# ---
automation: !include malibu-point/automations.yaml
script: !include malibu-point/scripts.yaml
scene: !include malibu-point/scenes.yaml

# ---
# Interfaces
# ---
frontend:
  themes: !include_dir_named malibu-point/themes/

google_assistant:
  project_id: home-assistant-140f3
  service_account: !include malibu-point/SERVICE_ACCOUNT.JSON
  report_state: true
  exposed_domains:
    - alarm_control_panel
    - switch
    - camera
  secure_devices_pin: !secret google_secure_devices_pin

# ---
# Other
# ---
group: !include malibu-point/groups.yaml

tts:
  - platform: google_translate
