# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

sensor:
  - platform: example_sensor
alarm_control_panel:
  - platform: smaug

frontend:
  themes: !include google-home.yaml

# Example configuration.yaml entry
google_assistant:
  project_id: home-assistant-140f3
  service_account: !include SERVICE_ACCOUNT.JSON
  report_state: true
  exposed_domains:
    # - switch
    - switch
  #secure_devices_pin: "0"
