# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# ---
# Entities
# ---
sensor: !include_dir_merge_list includes/entities/sensor
alarm_control_panel: !include_dir_merge_list includes/entities/alarm_control_panel
camera: !include_dir_merge_list includes/entities/camera
media_player: !include_dir_merge_list includes/entities/media_player
climate: !include_dir_merge_list includes/entities/climate

input_boolean: !include_dir_merge_named includes/entities/input_boolean
input_select: !include_dir_merge_named includes/entities/input_select
counter: !include_dir_merge_named includes/entities/counter

glances: !include includes/entities/glances.yaml
tuya: !include includes/entities/tuya.yaml

# ---
# Services
# ---
rest_command: !include_dir_merge_named includes/services/rest_command

# ---
# Automations
# ---
script: !include includes/scripts.yaml
scene: !include includes/scenes.yaml
automation: !include_dir_merge_list includes/automations

# ---
# Interfaces
# ---
frontend:
  themes: !include_dir_named includes/themes/

google_assistant:
  project_id: home-assistant-140f3
  service_account: !include SERVICE-ACCOUNT.json
  report_state: true
  exposed_domains:
    - switch
  entity_config: !include_dir_merge_named includes/google_assistant
  secure_devices_pin: !secret google_secure_devices_pin

# ---
# Other
# ---
group: !include includes/groups.yaml

http:
  use_x_forwarded_for: true
  trusted_proxies: 127.0.0.1

tts:
  - platform: google_translate
