- alias: 'Amnirana triggered Mobile Push Notification'
  trigger:
    - platform: numeric_state
      entity_id: counter.amnirana_motion_detector
      above: 0
  action:
    service: notify.mobile_app_aquila
    data:
      message: "Motion was Detected"
      title: "Amnirana Motion Detection"

- alias: '[GLUE] if amnirana input_boolean = off then reset amnirana counter  (a)'
  trigger:
    - platform: state
      entity_id: input_boolean.amnirana_motion_detector
      to: 'off'
  action:
    service: counter.reset
    entity_id: counter.amnirana_motion_detector

- alias: '[GLUE] if amnirana counter = 0 then amnirana input_boolean = off'
  trigger:
    - platform: state
      entity_id: counter.amnirana_motion_detector
      to: '0'
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.amnirana_motion_detector
