- alias: 'Leaving Home'
  trigger:
    - platform: state
      entity_id: person.mathijs
      to: 'not_home'
  action:
    - service: alarm_control_panel.alarm_arm_away
      entity_id: alarm_control_panel.smaug
    - service: switch.turn_off
      entity_id: switch.bedroom_light
    - service: switch.turn_off
      entity_id: switch.living_light
    - service: switch.turn_off
      entity_id: switch.office_light
    - service: switch.turn_off
      entity_id: switch.office_floor_fan
    - service: media_player.turn_off
      entity_id: media_player.hyla
    - service: media_player.turn_off
      entity_id: media_player.taricha
