- alias: '[ALIAS] if taricha_ui = chromecast then taricha_ui = hyla'
  trigger:
    - platform: state
      entity_id: input_select.taricha_ui
      to: 'chromecast'
  condition:
    - condition: template
      value_template: "{{ states.input_select.taricha.state != '3' }}"
  action:
    - service: input_select.select_option
      entity_id: input_select.taricha_ui
      data:
        option: 'hyla'

- alias: '[ALIAS] if taricha_ui = raspberry pi then taricha_ui = ailurus'
  trigger:
    - platform: state
      entity_id: input_select.taricha_ui
      to: 'raspberry pi'
  action:
    - service: input_select.select_option
      entity_id: input_select.taricha_ui
      data:
        option: 'ailurus'
