- alias: 'Glue: taricha (t) and taricha_ui (a) if media_player changed to 0'
  trigger:
    - platform: state
      entity_id: input_select.taricha
      to: '0'
  condition:
    - condition: template
      value_template: "{{ states.input_select.taricha_ui.state != 'default' }}"
  action:
    - service: input_select.select_option
      entity_id: input_select.taricha_ui
      data:
        option: 'default'

- alias: 'Glue: taricha (t) and taricha_ui (a) if media_player changed to 1'
  trigger:
    - platform: state
      entity_id: input_select.taricha
      to: '1'
  condition:
    - condition: template
      value_template: "{{ states.input_select.taricha_ui.state != 'ailurus' }}"
  action:
    - service: input_select.select_option
      entity_id: input_select.taricha_ui
      data:
        option: 'ailurus'

- alias: 'Glue: taricha (t) and taricha_ui (a) if media_player changed to 2'
  trigger:
    - platform: state
      entity_id: input_select.taricha
      to: '2'
  condition:
    - condition: template
      value_template: "{{ states.input_select.taricha_ui.state != 'hyla' }}"
  action:
    - service: input_select.select_option
      entity_id: input_select.taricha_ui
      data:
        option: 'hyla'

- alias: 'Glue: taricha (t) and taricha_ui (a) if media_player changed to 3'
  trigger:
    - platform: state
      entity_id: input_select.taricha
      to: '3'
  condition:
    - condition: template
      value_template: "{{ states.input_select.taricha_ui.state != 'external' }}"
  action:
    - service: input_select.select_option
      entity_id: input_select.taricha_ui
      data:
        option: 'external'

- alias: 'Glue: Taricha taricha_ui (t) and taricha (a) if ui changed to default'
  trigger:
    - platform: state
      entity_id: input_select.taricha_ui
      to: 'default'
  condition:
    - condition: template
      value_template: "{{ states.input_select.taricha.state != '0' }}"
  action:
    - service: media_player.select_source
      entity_id: media_player.taricha
      data:
        source: '0'

- alias: 'Glue: taricha_ui (t) and taricha (a) if ui changed to ailurus'
  trigger:
    - platform: state
      entity_id: input_select.taricha_ui
      to: 'ailurus'
  condition:
    - condition: template
      value_template: "{{ states.input_select.taricha.state != '1' }}"
  action:
    - service: media_player.select_source
      entity_id: media_player.taricha
      data:
        source: '1'

- alias: 'Glue: taricha_ui (t) and taricha (a) if ui changed to hyla'
  trigger:
    - platform: state
      entity_id: input_select.taricha_ui
      to: 'hyla'
  condition:
    - condition: template
      value_template: "{{ states.input_select.taricha.state != '2' }}"
  action:
    - service: media_player.select_source
      entity_id: media_player.taricha
      data:
        source: '2'

- alias: 'Glue: taricha_ui (t) and taricha (a) if ui changed to external'
  trigger:
    - platform: state
      entity_id: input_select.taricha_ui
      to: 'external'
  condition:
    - condition: template
      value_template: "{{ states.input_select.taricha.state != '3' }}"
  action:
    - service: media_player.select_source
      entity_id: media_player.taricha
      data:
        source: '3'
