- alias: 'Auto-arm S.M.A.U.G.'
  trigger:
    - platform: state
      entity_id: person.mathijs
      to: 'not_home'
  action:
    - service: alarm_control_panel.alarm_arm_away
      entity_id: alarm_control_panel.smaug

- alias: 'Auto-disarm S.M.A.U.G.'
  trigger:
    - platform: state
      entity_id: person.mathijs
      to: 'home'
  action:
    - service: alarm_control_panel.alarm_disarm
      entity_id: alarm_control_panel.smaug
