# taricha is a panasonic tv without ip stack which can be connected to home assistant
# through a G.I.N.G.E.R. instance with an HDMI-CEC trick.
- platform: universal
  name: taricha
  children:
    - media_player.hyla
  commands:
    turn_on:
      service: rest_command.turn_on_taricha
    turn_off:
      service: rest_command.turn_off_taricha
    select_source:
      service: rest_command.select_source_taricha
      data_template:
        source: '{{ source }}'
  attributes:
    state: input_boolean.taricha
    source: input_select.taricha
    source_list: "['0', '1', '2', '3']"
