- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /
    - type: disk_use
      arg: /
    - type: disk_free
      arg: /
    - type: memory_use_percent
    - type: memory_use
    - type: memory_free
    - type: swap_use_percent
    - type: swap_use
    - type: swap_free
    - type: load_1m
    - type: load_5m
    - type: load_15m
    - type: throughput_network_in
      arg: enp9s0
    - type: throughput_network_out
      arg: enp9s0
    - type: ipv4_address
      arg: enp9s0
    - type: ipv6_address
      arg: enp9s0
    - type: throughput_network_in
      arg: wlp5s0b1
    - type: throughput_network_out
      arg: wlp5s0b1
    - type: ipv4_address
      arg: wlp5s0b1
    - type: ipv6_address
      arg: wlp5s0b1
    - type: processor_use
    - type: last_boot
